apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-sample
  labels:
    app: nodejs-sample
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nodejs-sample
  template:
    metadata:
      labels:
        app: nodejs-sample
    spec:
      containers:
      - image: 874542566772.dkr.ecr.us-east-1.amazonaws.com/nodejs-sample:latest
        name: nodejs-sample
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: '50Mi'
            cpu: '50m'
          limits:
            memory: '50Mi'
            cpu: '50m'
        securityContext:
          privileged: false
          #readOnlyRootFilesystem: false # guestbook neet to write to /var/run/apache2/apache2.pid
          allowPrivilegeEscalation: false