apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: team-nguyen
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
    #   nodeSelector:
    #     "beta.kubernetes.io/os": linux
      containers:
        - name: nodejs
          # image: mreferre/yelb-ui:0.7
          image: 874542566772.dkr.ecr.us-east-1.amazonaws.com/nodejs-sample:1.0.0
          ports:
            - containerPort: 80