apiVersion: v1
kind: Service
metadata:
  name: nodejs
  namespace: team-nguyen
  labels:
    app: nodejs
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nodejs