apiVersion: v1
kind: Service
metadata:
  name: nodejs-sample
  labels:
    app: nodejs-sample
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nodejs-sample
